export const BU_LIST = [
  "HO/DR", 
  "CWC", 
  "RAMAT", 
  "EFS", 
  "ETS", 
  "Alrashed Food", 
  "Alrashed Tires", 
  "Jana Marine / Tanajib", 
  "Industrials (Steel, Fast)", 
  "Alrashed Wood", 
  "Admirals", 
  "YAUMI", 
  "BMD", 
  "Saudi Filter", 
  "cement", 
  "Insuwrap", 
  "EFS/ETS", 
  "Ubmksa", 
  "Polystyrene"
]; 